//
//  RateRouter.swift
//  CurrencyViewer
//
//  Created by Dmitrii Leksashov on 28/05/2019.
//  Copyright (c) 2019 Dmitrii Leksashov. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol RateRoutingLogic {
}

protocol RateDataPassing {
    var dataStore: RateDataStore? { get }
}

class RateRouter: NSObject, RateRoutingLogic, RateDataPassing {
    weak var viewController: RateViewController?
    var dataStore: RateDataStore?
}
