//
//  RatePresenter.swift
//  CurrencyViewer
//
//  Created by Dmitrii Leksashov on 28/05/2019.
//  Copyright (c) 2019 Dmitrii Leksashov. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol RatePresentationLogic {
    func presentSomething(response: Rate.Something.Response)
}

class RatePresenter: RatePresentationLogic {
    weak var viewController: RateDisplayLogic?
    
    // MARK: Do something
    func presentSomething(response: Rate.Something.Response) {
        let viewModel = Rate.Something.ViewModel()
        viewController?.displaySomething(viewModel: viewModel)
    }
}
