//
//  RateInteractor.swift
//  CurrencyViewer
//
//  Created by Dmitrii Leksashov on 28/05/2019.
//  Copyright (c) 2019 Dmitrii Leksashov. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol RateBusinessLogic {
    func doSomething(request: Rate.Something.Request)
}

protocol RateDataStore {
    //var name: String { get set }
}

class RateInteractor: RateBusinessLogic, RateDataStore {
    var presenter: RatePresentationLogic?
    var worker: RateWorker?
    //var name: String = ""
    
    // MARK: Do something
    func doSomething(request: Rate.Something.Request) {
        worker = RateWorker()
        worker?.doSomeWork()
        
        let response = Rate.Something.Response()
        presenter?.presentSomething(response: response)
    }
}
