//
//  HomeInteractor.swift
//  CurrencyViewer
//
//  Created by Dmitrii Leksashov on 28/05/2019.
//  Copyright (c) 2019 Dmitrii Leksashov. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol HomeBusinessLogic {
    func prepareItems(request: Home.Items.Request)
    func prepareSelectedItem(request: Home.SelectedItem.Request)
}

protocol HomeDataStore {
    var selectedDate: Date { get set }
}

class HomeInteractor: HomeBusinessLogic, HomeDataStore {
    var presenter: HomePresentationLogic?
    var selectedDate: Date = Date()
    var dates = [Date]()
    
    func prepareItems(request: Home.Items.Request) {
        for step in 0 ... Constants.countOfDate {
            guard let newDate = Date().removal(value: step, component: .day) else {
                break
            }
            dates.append(newDate)
        }
        let stringDates = dates.map { $0.toString(with: .dayMonthYear) }
        let response = Home.Items.Response(dates: stringDates)
        presenter?.presentItems(response: response)
    }
    
    func prepareSelectedItem(request: Home.SelectedItem.Request) {
        selectedDate = dates[request.index]
        let response = Home.SelectedItem.Response()
        presenter?.presentSelectedItem(response: response)
    }
}
