//
//  HomeRouter.swift
//  CurrencyViewer
//
//  Created by Dmitrii Leksashov on 28/05/2019.
//  Copyright (c) 2019 Dmitrii Leksashov. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol HomeRoutingLogic {
    func routeToRateScreen()
}

protocol HomeDataPassing {
    var dataStore: HomeDataStore? { get }
}

class HomeRouter: NSObject, HomeRoutingLogic, HomeDataPassing {
    weak var viewController: HomeViewController?
    var dataStore: HomeDataStore?
    
    // MARK: Routing
    func routeToRateScreen() {
        let storyboard = UIStoryboard(name: "Rate", bundle: nil)
        
        guard let rateViewController = storyboard.instantiateInitialViewController() as? RateViewController,
        let sourceDataSource = dataStore,
        var destinationDataSource = rateViewController.router?.dataStore
        else {
                return
        }
        passDataToRateScreen(source: sourceDataSource, destination: &destinationDataSource)
        navigateToRateScreen(destination: rateViewController)
        
    }

    
     // MARK: Navigation
    func navigateToRateScreen(destination: RateViewController) {
        viewController?.show(destination, sender: nil)
    }
    
     // MARK: Passing data
    func passDataToRateScreen(source: HomeDataStore, destination: inout RateDataStore) {
        destination.selectedDate = source.selectedDate
    }
}
