//
//  HomePresenter.swift
//  CurrencyViewer
//
//  Created by Dmitrii Leksashov on 28/05/2019.
//  Copyright (c) 2019 Dmitrii Leksashov. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol HomePresentationLogic {
    func presentItems(response: Home.Items.Response)
    func presentSelectedItem(response: Home.SelectedItem.Response)
}

class HomePresenter: HomePresentationLogic {
    weak var viewController: HomeDisplayLogic?
    
    func presentItems(response: Home.Items.Response) {
        let viewModel = Home.Items.ViewModel(dates: response.dates)
        viewController?.reloadData(viewModel: viewModel)
    }
    
    func presentSelectedItem(response: Home.SelectedItem.Response) {
        let viewModel = Home.SelectedItem.ViewModel()
        viewController?.displayRateScreen(viewModel: viewModel)
    }
}
