//
//  HomeModels.swift
//  CurrencyViewer
//
//  Created by Dmitrii Leksashov on 28/05/2019.
//  Copyright (c) 2019 Dmitrii Leksashov. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Home {
    enum Items {
        struct Request { }
        struct Response {
            var dates: [String]
        }
        struct ViewModel {
            var dates: [String]
        }
    }
    
    enum SelectedItem {
        struct Request {
            var index: Int
        }
        struct Response { }
        struct ViewModel { }
    }
}
